eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka

app:
  frontend-base-url: ${SO_FRONTEND_BASE_URL}
  gateway-base-url: http://gateway-server:8888

spring:
  security:     #bff-server'i keycloak'a tanitiyoruz
    oauth2:
      client:
        provider:  #keycloak bir provider (auth providerı)
          keycloak:
            issuer-uri: http://keycloak:8585/realms/parena
            authorization-uri: ${SO_KEYCLOAK_DEV_HOSTNAME}/realms/parena/protocol/openid-connect/auth #browser-routing (internal)
            token-uri: http://keycloak:8585/realms/parena/protocol/openid-connect/token  #bff: token almak icin dockerdaki keycloaka gider (internal)
            jwk-set-uri: http://keycloak:8585/realms/parena/protocol/openid-connect/certs #bff: jwt imzalarını dogrulamak icin keycloaka gider (internal)
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: bff-server    #keycloak'ta olusturdugumuz client'in id'si.     (confidential-client)
            client-secret: ${SO_BFF_CLIENT_SECRET}  #client'e atanmıs secret
            redirect-uri: "${SO_BFF_BASE_URL}/login/oauth2/code/{registrationId}"   #baseUrl:http://localhost:8989, registrationId:keycloak
            authorization-grant-type: authorization_code
            scope:          #giriş yapmıs kullanıcıdan hangi bilgileri alalım
              - openid      #jwt bilgileri icin gerekli
              - profile
              - email
              - roles
  session:
    redis:
      namespace: parena:bff:session
    timeout: 30m
  data:
    redis:
      host: redis
      port: 6379
      password: ${SO_REDIS_PASSWORD}

logging:
  level:
    org.springframework.security: DEBUG