eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    instance:
      prefer-ip-address: true

app:
  frontend-base-url: ${SO_FRONTEND_BASE_URL}
  gateway-base-url: http://localhost:8888

spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: bff-server
            client-secret: ${SO_BFF_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            scope: openid, profile, email, roles
            redirect-uri: "${SO_BFF_BASE_URL}/login/oauth2/code/{registrationId}"
        provider:
          keycloak:
            issuer-uri: http://keycloak:8585/realms/parena

  session:
    redis:
      namespace: parena:bff:session
    timeout: 30m

  data:
    redis:
      host: redis
      port: 6379
      password: ${SO_REDIS_PASSWORD}

logging:
  level:
    org.springframework.security: DEBUG