spring:
  application:
    name: user-service
  profiles:
    active: docker
  config:
    import: configserver:${SO_CONFIG_URI:http://localhost:8787}
  cloud: #config-server security ile korunuyor, config servera baglanırken basit authentication yapılacak.
    config:
      username: ${SO_CONFIG_SECURITY_USER}
      password: ${SO_CONFIG_SECURITY_PASSWORD}