#eureka client localdeki eureka servera bağlansın.
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


#user-service keycloak bağlantısı.
keycloak:
  realm: parena
  auth-server-url: http://localhost:8585
  admin-client-id: user-service
  admin-client-secret: ${SO_USER_SERVICE_CLIENT_SECRET}

  client-id: bff-server
  email-verified-redirect-uri: ${SO_FRONTEND_BASE_URL}/email-dogrulandi

spring:
  #db config (postgresql)
  datasource:
    url: jdbc:postgresql://localhost:5432/user_service
    username: ${SO_USER_SERVICE_DB_USER}
    password: ${SO_USER_SERVICE_DB_PASSWORD}

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8585/realms/parena/protocol/openid-connect/certs

  #hibernate & orm
  jpa:
    hibernate:
      ddl-auto: validate   # şema Flyway'in sorumluluğunda
      open-in-view: false
  flyway:
    enabled: true