// This file is auto-generated by the `update-kc-gen` command. Do not edit it manually.
// Hash: b874ef3020a8108ad84e17164f42357aae05a10104b061c9896613ce9ed0be2c


/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

import { lazy, Suspense, type ReactNode } from "react";

export type ThemeName = "app";

export const themeNames: ThemeName[] = ["app"];

export type KcEnvName = "APP_URL" | "WEBSITE_URL";

export const kcEnvNames: KcEnvName[] = ["APP_URL", "WEBSITE_URL"];

export const kcEnvDefaults: Record<KcEnvName, string> = {
  "APP_URL": "https://app.parena.com.tr",
  "WEBSITE_URL": "https://parena.com.tr"
};

/**
 * NOTE: Do not import this type except maybe in your entrypoint. 
 * If you need to import the KcContext import it either from src/login/KcContext.ts or src/account/KcContext.ts.
 * Depending on the theme type you are working on.
 */
export type KcContext =
    | import("./login/KcContext").KcContext
    ;

declare global {
    interface Window {
        kcContext?: KcContext;
    }
}

export const KcLoginPage = lazy(() => import("./login/KcPage"));

export function KcPage(
    props: {
        kcContext: KcContext;
        fallback?: ReactNode;
    }
) {
    const { kcContext, fallback } = props;
    return (
        <Suspense fallback={fallback}>
            {(() => {
                switch (kcContext.themeType) {
                    case "login": return <KcLoginPage kcContext={kcContext} />;
                }
            })()}
        </Suspense>
    );
}

// NOTE: This is exported here only because in Webpack environnement it works differently
export const BASE_URL = import.meta.env.BASE_URL

// NOTE: This is only exported here because you're supposed to import type from different packages
// Depending of if you are using Vite, Webpack, ect...
export type { Meta, StoryObj } from "@storybook/react-vite";
