# actuator endpointlerini dışarıya açar -> beans,caches,health,info,env,metrics...
# actuator endpoints -> uygulamanızı izlemenize ve onunla etkileşim kurmanıza olanak tanır.
management:
  endpoints:
    access:
      default: none        #endpoint’leri varsayılan olarak devre dışı bırakır.
    web:
      exposure:
        include:          #web üzerinden yalnızca belirtilenleri yayınlar.
          - health

  endpoint:
    health:
      access: read-only
      show-details: never