spring:
  application:
    name: config-server
  profiles:
    active: git
  security:           #config-server basic auth -> config servera herkes erişemez.
    user:
      name: ${SO_CONFIG_SECURITY_USER}
      password: ${SO_CONFIG_SECURITY_PASSWORD}
  cloud:
    config:
      server:
        git:
          uri: ${SO_CONFIG_GIT_URI}
          default-label: ${SO_CONFIG_GIT_BRANCH:main}
          username: ${SO_CONFIG_GIT_USERNAME}
          password: ${SO_CONFIG_GIT_TOKEN}
          search-paths:
            - backend/configurations/
            - backend/configurations/{application}
          force-pull: true
          clone-on-start: true
        native:
         search-locations: [ ]

server:
  port: 8787